### ISSUE TITLE
你好，请问这是ts写的吗？可以编译成普通的js版本吗？

### ISSUE THREAD

**Issue by Gala-1024** [maolion/weboot#1]
我想直接在页面里面通过<script src="weboot.js"></script>调用

**Comment by maolion** [comment]
@cgygd 这个weboot 的用途是把指定html文件里原来的 ``` <link rel="stylesheet" href="..." />``` ```<style>...</style>``` ```<script src="..."></script>``` ```<script>...</script>```  的定义 自动转成 使用js控制加载的方式.  可以参考下 [weboot-example](https://github.com/maolion/weboot-example)

```bootstrap``` 部分的代码目前只支持 嵌入到目标的 html 结构里，不支持外部引用

源代码是用 ```typescript``` 写的，编译的代码可以执行 ```yarn build``` 得到 会输出到 ```dist``` 目录
